### ISSUE TITLE
should not require a restart when devmode

### ISSUE THREAD

**Issue by maxandersen** [quarkus-extension/quarkus-ngrok-extension#3]
in devmode ngrok is reinitialized and unless you setup ngrok auth it will trigger a new url creation. optimally would be it checks if tunnel already exist and reuse that. likewise during restart don't kill ngrok.

**Comment by previousdeveloper** [comment]
In hot reload mode it reuses the connection which doesn't create a new connection. Full process restarting the is required new connection  I think

**Comment by maxandersen** [comment]
hmm - thats not what I experienced - seem to get a new one. I'll try again ;)
